# This Dockerfile builds the Flask part only.

FROM python:3.9
WORKDIR /app

COPY service/requirements.txt service/requirements_ml.txt service/app.py ./
RUN pip install -r ./requirements.txt
RUN pip install -r ./requirements_ml.txt

ENV FLASK_APP app.py
CMD ["flask","run"]

