# Build step #1: build the React front end
FROM node:16-alpine as build-step

WORKDIR /app/ui
COPY ui/ ./

# Install dependencies
RUN yarn install

RUN npm run build
ENV PATH /app/ui/node_modules/.bin:$PATH

# Build step#2: deploy
EXPOSE 3000
CMD npm start