# This Dockerfile builds the Flask part only.

FROM python:3.7
WORKDIR /app/service

# COPY sourcepath destinationpath
COPY service ./
RUN pip install -r ./requirements.txt
RUN pip install -r ./requirements_ml.txt

# RUN ls -la ./*

ENV FLASK_APP ./app.py
CMD ["flask","run"]

